name: Ubuntu - Rapidgator1

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: ubuntu-latest

    steps:
      - name: Downloading & Installing Essentials
        run: |
          wget -O rpgl.sh "https://raw.githubusercontent.com/diva22001/rapidgator2/refs/heads/main/rpgl.sh?token=GHSAT0AAAAAADGBDO4YWUMLSN4SP4QJ3RWI2FCBPPA"
          chmod +x rpgl.sh
          ./rpgl.sh
