name: Rapidgator to Google Drive

on:
  workflow_dispatch:
    inputs:
      rapidgator_urls:
        description: "Masukkan URL Rapidgator (pisahkan dengan koma)"
        required: true
        default: "https://rapidgator.net/file/abc123,https://rapidgator.net/file/xyz456"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 rclone python3-pip
          pip install requests

      - name: Configure Rclone
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}  # Simpan konfig rclone.conf di Secrets
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf

      - name: Download Files from Rapidgator
        run: |
          # Download script rapidgator.py
          wget -O rapidgator.py https://raw.githubusercontent.com/diva22001/rapidgator2/refs/heads/main/rapidgator.py?token=GHSAT0AAAAAADGBDO4ZGOBYQDEHOZDWD4SI2FCCL5A

          # Buat file input dari URL
          echo "${{ github.event.inputs.rapidgator_urls }}" | tr ',' '\n' > urls.txt

          # Jalankan downloader
          python3 rapidgator.py --input-file urls.txt

      - name: Upload to Google Drive
        run: |
          rclone copy ./download diva22001:/ -P --stats-one-line
